apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.4.2
        ports:
          - containerPort: 3100
        args:
          - -config.file=/etc/loki/loki-config.yaml
        volumeMounts:
          - name: config-volume
            mountPath: /d/clust/loki  # Mount the volume at this path
      volumes:
        - name: config-volume
          configMap:
            name: loki-config  # Make sure this ConfigMap exists
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  ports:
    - port: 3100
  selector:
    app: loki
